# Generated by Django 6.0.3 on 2026-03-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='IngestionRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('persisted', 'Persisted'), ('failed', 'Failed'), ('remove', 'Remove')], default='pending', max_length=20)),
                ('response_id', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingestion Raw',
                'verbose_name_plural': 'Ingestion Raw Data',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Rate Type',
                'verbose_name_plural': 'Rate Types',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('effective_date', models.DateField()),
                ('ingestion_ts', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_response_id', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.provider')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.ratetype')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'indexes': [models.Index(fields=['effective_date', 'currency', 'provider'], name='rates_rate_effecti_e21ddb_idx')],
            },
        ),
    ]
