# Generated by Django 6.0.3 on 2026-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngestionRaw',
            new_name='IngestRaw',
        ),
        migrations.AlterModelOptions(
            name='ingestraw',
            options={'verbose_name': 'Ingest Raw', 'verbose_name_plural': 'Ingest Raw Data'},
        ),
    ]
