# Generated by Django 6.0.3 on 2026-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_rename_ingestionraw_ingestraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rate',
            name='raw_response_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
