# Generated by Django 6.0.3 on 2026-03-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_currency_aliases_alter_rate_raw_response_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestraw',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('success', 'Success')], default='pending', max_length=20),
        ),
    ]
