# Generated by Django 6.0.3 on 2026-03-29 04:44

import json
from django.db import migrations


def add_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )

    PeriodicTask.objects.update_or_create(
        name="Hourly seed_data",
        defaults={
            "crontab": schedule,
            "task": "rates.tasks.run_seed_data_task",
            "args": json.dumps([]),
            "kwargs": json.dumps({}),
        },
    )


def remove_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="Hourly seed_data").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0004_alter_ingestraw_status"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_periodic_task, remove_periodic_task),
    ]
